apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyhchart.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "pyhchart.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
      {{- toYaml .Values.service.annotations | nindent 6 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $item := .Values.secrets }}
    {{ $item.name }}: {{ $item.value | quote}}
  {{- end }}  
